# TCL File Generated by Component Editor 13.0sp1
# Fri Jun 10 14:34:11 BRT 2016
# DO NOT MODIFY


# 
# matriz_avalon_interface "matriz" v1.0
#  2016.06.10.14:34:11
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module matriz_avalon_interface
# 
set_module_property DESCRIPTION ""
set_module_property NAME matriz_avalon_interface
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "My Own IP Cores"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME matriz
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL matriz_avalon_interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file matriz_avalon_interface.vhd VHDL PATH matriz_avalon_interface.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter rows POSITIVE 4
set_parameter_property rows DEFAULT_VALUE 4
set_parameter_property rows DISPLAY_NAME rows
set_parameter_property rows TYPE POSITIVE
set_parameter_property rows UNITS None
set_parameter_property rows HDL_PARAMETER true
add_parameter cols POSITIVE 4
set_parameter_property cols DEFAULT_VALUE 4
set_parameter_property cols DISPLAY_NAME cols
set_parameter_property cols TYPE POSITIVE
set_parameter_property cols UNITS None
set_parameter_property cols HDL_PARAMETER true
add_parameter data_width POSITIVE 32
set_parameter_property data_width DEFAULT_VALUE 32
set_parameter_property data_width DISPLAY_NAME data_width
set_parameter_property data_width TYPE POSITIVE
set_parameter_property data_width UNITS None
set_parameter_property data_width HDL_PARAMETER true


# 
# display items
# 


# 
# connection point aslave
# 
add_interface aslave avalon end
set_interface_property aslave addressUnits WORDS
set_interface_property aslave associatedClock clock_sink
set_interface_property aslave associatedReset reset_sink
set_interface_property aslave bitsPerSymbol 8
set_interface_property aslave burstOnBurstBoundariesOnly false
set_interface_property aslave burstcountUnits WORDS
set_interface_property aslave explicitAddressSpan 0
set_interface_property aslave holdTime 0
set_interface_property aslave linewrapBursts false
set_interface_property aslave maximumPendingReadTransactions 0
set_interface_property aslave readLatency 0
set_interface_property aslave readWaitTime 1
set_interface_property aslave setupTime 0
set_interface_property aslave timingUnits Cycles
set_interface_property aslave writeWaitTime 0
set_interface_property aslave ENABLED true
set_interface_property aslave EXPORT_OF ""
set_interface_property aslave PORT_NAME_MAP ""
set_interface_property aslave SVD_ADDRESS_GROUP ""

add_interface_port aslave avs_aslave_read read Input 1
add_interface_port aslave avs_aslave_write write Input 1
add_interface_port aslave avs_aslave_address address Input 1
add_interface_port aslave avs_aslave_writedata writedata Input data_width
add_interface_port aslave avs_aslave_readdata readdata Output data_width
set_interface_assignment aslave embeddedsw.configuration.isFlash 0
set_interface_assignment aslave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment aslave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment aslave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point pwms
# 
add_interface pwms conduit end
set_interface_property pwms associatedClock clock_sink
set_interface_property pwms associatedReset reset_sink
set_interface_property pwms ENABLED true
set_interface_property pwms EXPORT_OF ""
set_interface_property pwms PORT_NAME_MAP ""
set_interface_property pwms SVD_ADDRESS_GROUP ""

add_interface_port pwms coe_pwms_export export Output rows*cols


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink csi_csink_clock clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rsi_rsink_resetn reset_n Input 1

